[build]
  command = "node build.js"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/donors.html"
  to = "/"
  status = 301
[[redirects]]
  from = "/kz/donors.html"
  to = "/kz/"
  status = 301
[[redirects]]
  from = "/en/donors.html"
  to = "/en/"
  status = 301
[[redirects]]
  from = "/news-item.html"
  to = "/press.html"
  status = 301
[[redirects]]
  from = "/kz/news-item.html"
  to = "/kz/press.html"
  status = 301
[[redirects]]
  from = "/en/news-item.html"
  to = "/en/press.html"
  status = 301
