// Тексты шаблонов документов для грантовой заявки (RU / KZ / EN)
module.exports = {
  ru: {
    fund: 'Корпоративный фонд целевого капитала «Эндаумент-фонд науки и образования»',
    site: 'endowment-fund.kz · endowment@alageum.com',
    hint: 'Поля в квадратных скобках заполните или удалите. Серые подсказки можно удалить после заполнения.',
    sign: ['Подпись', 'Ф.И.О.', 'Дата', 'М.П. (для юридических лиц)'],
    app: {
      file: '01-zayavka.docx', title: 'ЗАЯВКА', sub: 'на получение благотворительной помощи (гранта) Фонда',
      s1: '1. Сведения о заявителе',
      f1: ['Наименование организации / Ф.И.О. заявителя', 'БИН / ИИН', 'Юридический и фактический адрес', 'Первый руководитель (Ф.И.О., должность)', 'Руководитель проекта (Ф.И.О., должность)', 'Контактный телефон', 'E-mail'],
      s2: '2. Сведения о проекте',
      progL: 'Благотворительная программа Фонда', progs: ['Поддержка образования', 'Поддержка науки, научной и научно-технической деятельности', 'Поддержка инновационной деятельности и коммерциализации технологий (в т.ч. AI Sana)'],
      f2: ['Название проекта', 'Направление поддержки', 'Срок реализации (начало — окончание)', 'Запрашиваемая сумма, ₸', 'Софинансирование, ₸ (источник), если есть', 'Общая стоимость проекта, ₸'],
      s3: '3. Краткая аннотация проекта', s3h: 'До 500 знаков: проблема, цель, что будет сделано и какой результат получат выгодополучатели.',
      s4: '4. Ожидаемые результаты', s4h: 'Перечислите 3–5 измеримых результатов (подробно — в описании проекта).',
      s5: '5. Иное финансирование', s5h: 'Укажите, получал ли проект или его отдельные расходы финансирование из государственных, частных или иных источников, либо подана ли заявка в другие фонды. Если нет — напишите «нет».',
      s6: '6. Прилагаемые документы',
      att: ['Описание проекта (до 10 страниц)', 'Смета расходов', 'CV руководителя и участников проекта', 'Письмо поддержки от организации', 'Иные документы: [перечислите]'],
      s7: '7. Подтверждения заявителя',
      conf: ['Сведения в заявке и приложениях достоверны и полны.', 'Отсутствует конфликт интересов с работниками и органами Фонда (либо он раскрыт в приложении).', 'Одни и те же расходы не финансируются из других источников (отсутствует двойное финансирование).', 'Заявитель согласен на мониторинг, представление отчётности и проверку целевого использования средств.', 'Заявитель согласен на сбор и обработку персональных данных в объёме, необходимом для рассмотрения заявки.'],
    },
    desc: {
      file: '02-opisanie-proekta.docx', title: 'ОПИСАНИЕ ПРОЕКТА', sub: 'Объём — не более 10 страниц (шрифт 12, интервал 1,15)',
      meta: ['Название проекта', 'Заявитель', 'Программа Фонда'],
      secs: [
        ['1. Актуальность и описание проблемы', 'Какую проблему решает проект, почему она важна для Казахстана, кто выгодополучатели. Приведите данные и ссылки на источники.'],
        ['2. Цель и задачи проекта', 'Одна цель и 3–5 конкретных задач.'],
        ['3. Новизна и значимость', 'Для научных проектов — научная новизна и гипотеза; для образовательных — чем проект лучше существующих решений; для инновационных — стадия готовности технологии (TRL) и рынок.'],
        ['4. Методология и подход', 'Как будут решаться задачи: методы, этапы, используемые данные и инфраструктура.'],
        ['5. Календарный план', null, 'plan'],
        ['6. Команда проекта', 'Руководитель и ключевые участники: роль в проекте, квалификация, занятость. CV прилагаются отдельно.'],
        ['7. Инфраструктура и ресурсы', 'Какие оборудование, лаборатории, данные и партнёры уже есть, что требуется приобрести.'],
        ['8. Ожидаемые результаты и показатели', null, 'kpi'],
        ['9. Риски и меры по их снижению', 'Научные, технические, финансовые, правовые и иные риски.'],
        ['10. Этика, данные и интеллектуальная собственность', 'Нужны ли этические одобрения и разрешения; как будут храниться данные; кому будут принадлежать результаты.'],
        ['11. Распространение и устойчивость результатов', 'Публикации, внедрение, как результаты будут использоваться после завершения финансирования.'],
      ],
      plan: ['№', 'Этап и мероприятия', 'Сроки', 'Результат этапа'],
      kpi: ['Показатель', 'Ед. изм.', 'Целевое значение', 'Способ подтверждения'],
      kpiEx: ['Пример: обучено педагогов', 'чел.', '120', 'Список, сертификаты'],
    },
    cv: {
      file: '04-cv.docx', title: 'РЕЗЮМЕ (CV) УЧАСТНИКА ПРОЕКТА', sub: 'Заполняется на руководителя и каждого ключевого участника проекта',
      f: ['Ф.И.О.', 'Роль в проекте', 'Место работы и должность', 'Учёная степень, звание (если есть)', 'E-mail, телефон', 'ORCID / Scopus ID / h-index (для научных проектов)'],
      edu: 'Образование', eduH: ['Годы', 'Учебное заведение', 'Специальность, степень'],
      job: 'Опыт работы (последние 10 лет)', jobH: ['Годы', 'Организация', 'Должность, основные обязанности'],
      pub: 'Ключевые публикации, проекты, гранты (до 5)', pubH: 'Для каждой позиции: название, год, роль, источник финансирования / журнал.',
      lang: 'Языки', other: 'Дополнительная информация',
    },
    letter: {
      file: '05-pismo-podderzhki.docx', blank: '[БЛАНК ОРГАНИЗАЦИИ]', out: 'Исх. № [___] от «__» ________ 20__ г.',
      to: ['Директору', 'Корпоративного фонда целевого капитала', '«Эндаумент-фонд науки и образования»'],
      title: 'ПИСЬМО ПОДДЕРЖКИ',
      body: [
        '[Наименование организации] выражает поддержку заявке [Ф.И.О. руководителя проекта / наименование заявителя] на участие в благотворительной программе Фонда «[название программы]» с проектом «[название проекта]».',
        'Проект соответствует приоритетам [организации] и направлен на [кратко — ожидаемый эффект для организации и выгодополучателей].',
        'В случае поддержки проекта [организация] обязуется: [предоставить доступ к инфраструктуре / лабораториям / данным; обеспечить участие сотрудников; осуществить софинансирование в размере ___ ₸; принять на баланс приобретённое имущество и обеспечить его эксплуатацию — оставьте нужное].',
        'Контактное лицо по проекту: [Ф.И.О., должность, телефон, e-mail].',
      ],
      signer: ['[Должность первого руководителя]', '[Подпись]', '[Ф.И.О.]'],
    },
    budget: {
      file: '03-smeta.xlsx', sheet: 'Смета', title: 'СМЕТА РАСХОДОВ ПРОЕКТА',
      meta: ['Заявитель', 'Название проекта', 'Программа Фонда', 'Срок реализации'],
      head: ['№', 'Статья расходов', 'Ед. изм.', 'Кол-во', 'Цена за ед., ₸', 'Сумма, ₸', 'Средства Фонда, ₸', 'Софинансирование, ₸', 'Обоснование'],
      cats: ['Оплата труда участников проекта (с налогами и обязательными платежами)', 'Оборудование, приборы, программное обеспечение', 'Материалы, реактивы, комплектующие', 'Услуги сторонних организаций (лабораторные, аналитические, переводческие и др.)', 'Полевые работы, экспедиции, сбор данных', 'Командировки, стажировки, участие в мероприятиях', 'Публикации, открытый доступ, распространение результатов', 'Правовая охрана результатов, разрешения, экспертизы', 'Накладные расходы (обоснованные, не более 10%)', 'Прочие прямые расходы'],
      ex: ['Пример: руководитель проекта, 0,5 ставки', 'мес.', 12, 450000, 'Средняя ставка по организации'],
      sub: 'Итого по статье', total: 'ИТОГО ПО ПРОЕКТУ', share: 'Доля средств Фонда',
      legend: 'Заполняйте жёлтые ячейки. Суммы считаются автоматически. Строку-пример замените своими данными; при необходимости добавляйте строки внутри статьи.',
    },
    zip: 'shablony-dokumentov.zip',
  },
  kz: {
    fund: '«Ғылым және білім эндаумент-қоры» корпоративтік нысаналы капитал қоры',
    site: 'endowment-fund.kz · endowment@alageum.com',
    hint: 'Тік жақшадағы жолдарды толтырыңыз немесе өшіріңіз. Сұр түсті кеңестерді толтырғаннан кейін өшіруге болады.',
    sign: ['Қолы', 'Т.А.Ә.', 'Күні', 'М.О. (заңды тұлғалар үшін)'],
    app: {
      file: '01-otinim.docx', title: 'ӨТІНІМ', sub: 'Қордың қайырымдылық көмегін (грантын) алуға',
      s1: '1. Өтініш беруші туралы мәліметтер',
      f1: ['Ұйымның атауы / өтініш берушінің Т.А.Ә.', 'БСН / ЖСН', 'Заңды және нақты мекенжайы', 'Бірінші басшы (Т.А.Ә., лауазымы)', 'Жоба жетекшісі (Т.А.Ә., лауазымы)', 'Байланыс телефоны', 'E-mail'],
      s2: '2. Жоба туралы мәліметтер',
      progL: 'Қордың қайырымдылық бағдарламасы', progs: ['Білім беруді қолдау', 'Ғылымды, ғылыми және ғылыми-техникалық қызметті қолдау', 'Инновациялық қызметті қолдау және технологияларды коммерцияландыру (оның ішінде AI Sana)'],
      f2: ['Жобаның атауы', 'Қолдау бағыты', 'Іске асыру мерзімі (басталуы — аяқталуы)', 'Сұралатын сома, ₸', 'Қоса қаржыландыру, ₸ (көзі), болса', 'Жобаның жалпы құны, ₸'],
      s3: '3. Жобаның қысқаша аннотациясы', s3h: '500 таңбаға дейін: мәселе, мақсат, не істелетіні және пайда алушылар қандай нәтиже алатыны.',
      s4: '4. Күтілетін нәтижелер', s4h: '3–5 өлшенетін нәтижені көрсетіңіз (толығырақ — жоба сипаттамасында).',
      s5: '5. Өзге қаржыландыру', s5h: 'Жоба немесе оның жекелеген шығыстары мемлекеттік, жеке немесе өзге көздерден қаржыландырылды ма, басқа қорларға өтінім берілді ме — көрсетіңіз. Болмаса, «жоқ» деп жазыңыз.',
      s6: '6. Қоса берілетін құжаттар',
      att: ['Жоба сипаттамасы (10 бетке дейін)', 'Шығыстар сметасы', 'Жетекші мен жоба қатысушыларының түйіндемесі', 'Ұйымның қолдау хаты', 'Өзге құжаттар: [тізімдеңіз]'],
      s7: '7. Өтініш берушінің растаулары',
      conf: ['Өтінімдегі және қосымшалардағы мәліметтер дұрыс және толық.', 'Қордың қызметкерлерімен және органдарымен мүдделер қақтығысы жоқ (не қосымшада ашылған).', 'Бір шығыстар өзге көздерден қаржыландырылмайды (қосарланған қаржыландыру жоқ).', 'Өтініш беруші мониторингке, есептілік ұсынуға және қаражаттың мақсатты пайдаланылуын тексеруге келіседі.', 'Өтініш беруші өтінімді қарау үшін қажетті көлемде дербес деректерді жинауға және өңдеуге келіседі.'],
    },
    desc: {
      file: '02-zhoba-sipattamasy.docx', title: 'ЖОБА СИПАТТАМАСЫ', sub: 'Көлемі — 10 беттен аспайды (қаріп 12, жоларалық 1,15)',
      meta: ['Жобаның атауы', 'Өтініш беруші', 'Қор бағдарламасы'],
      secs: [
        ['1. Өзектілігі және мәселенің сипаттамасы', 'Жоба қандай мәселені шешеді, ол Қазақстан үшін неге маңызды, пайда алушылар кім. Деректер мен дереккөздерге сілтемелер келтіріңіз.'],
        ['2. Жобаның мақсаты мен міндеттері', 'Бір мақсат және 3–5 нақты міндет.'],
        ['3. Жаңалығы мен маңызы', 'Ғылыми жобалар үшін — ғылыми жаңалығы мен гипотезасы; білім беру жобалары үшін — қолданыстағы шешімдерден артықшылығы; инновациялық жобалар үшін — технологияның дайындық деңгейі (TRL) және нарық.'],
        ['4. Әдістеме және тәсіл', 'Міндеттер қалай шешіледі: әдістер, кезеңдер, пайдаланылатын деректер мен инфрақұрылым.'],
        ['5. Күнтізбелік жоспар', null, 'plan'],
        ['6. Жоба командасы', 'Жетекші және негізгі қатысушылар: жобадағы рөлі, біліктілігі, жұмыспен қамтылуы. Түйіндемелер жеке қоса беріледі.'],
        ['7. Инфрақұрылым және ресурстар', 'Қандай жабдық, зертханалар, деректер мен серіктестер бар, нені сатып алу қажет.'],
        ['8. Күтілетін нәтижелер мен көрсеткіштер', null, 'kpi'],
        ['9. Тәуекелдер және оларды азайту шаралары', 'Ғылыми, техникалық, қаржылық, құқықтық және өзге тәуекелдер.'],
        ['10. Әдеп, деректер және зияткерлік меншік', 'Этикалық мақұлдаулар мен рұқсаттар қажет пе; деректер қалай сақталады; нәтижелер кімге тиесілі болады.'],
        ['11. Нәтижелерді тарату және тұрақтылығы', 'Жарияланымдар, енгізу, қаржыландыру аяқталғаннан кейін нәтижелер қалай пайдаланылады.'],
      ],
      plan: ['№', 'Кезең және іс-шаралар', 'Мерзімі', 'Кезең нәтижесі'],
      kpi: ['Көрсеткіш', 'Өлш. бірл.', 'Нысаналы мән', 'Растау тәсілі'],
      kpiEx: ['Мысалы: оқытылған педагогтар', 'адам', '120', 'Тізім, сертификаттар'],
    },
    cv: {
      file: '04-tuyindeme.docx', title: 'ЖОБА ҚАТЫСУШЫСЫНЫҢ ТҮЙІНДЕМЕСІ (CV)', sub: 'Жетекшіге және жобаның әрбір негізгі қатысушысына толтырылады',
      f: ['Т.А.Ә.', 'Жобадағы рөлі', 'Жұмыс орны және лауазымы', 'Ғылыми дәрежесі, атағы (болса)', 'E-mail, телефон', 'ORCID / Scopus ID / h-index (ғылыми жобалар үшін)'],
      edu: 'Білімі', eduH: ['Жылдар', 'Оқу орны', 'Мамандығы, дәрежесі'],
      job: 'Жұмыс тәжірибесі (соңғы 10 жыл)', jobH: ['Жылдар', 'Ұйым', 'Лауазымы, негізгі міндеттері'],
      pub: 'Негізгі жарияланымдар, жобалар, гранттар (5-ке дейін)', pubH: 'Әр позиция үшін: атауы, жылы, рөлі, қаржыландыру көзі / журнал.',
      lang: 'Тілдер', other: 'Қосымша ақпарат',
    },
    letter: {
      file: '05-qoldau-haty.docx', blank: '[ҰЙЫМНЫҢ БЛАНКІСІ]', out: 'Шығ. № [___] «__» ________ 20__ ж.',
      to: ['«Ғылым және білім эндаумент-қоры»', 'корпоративтік нысаналы капитал', 'қорының директорына'],
      title: 'ҚОЛДАУ ХАТЫ',
      body: [
        '[Ұйымның атауы] [жоба жетекшісінің Т.А.Ә. / өтініш берушінің атауы] өтінімін Қордың «[бағдарлама атауы]» қайырымдылық бағдарламасына «[жоба атауы]» жобасымен қатысуға қолдайтынын білдіреді.',
        'Жоба [ұйымның] басымдықтарына сәйкес келеді және [қысқаша — ұйым мен пайда алушылар үшін күтілетін әсер] бағытталған.',
        'Жоба қолдау тапқан жағдайда [ұйым] мына міндеттемелерді алады: [инфрақұрылымға / зертханаларға / деректерге қолжетімділік беру; қызметкерлердің қатысуын қамтамасыз ету; ___ ₸ мөлшерінде қоса қаржыландыру; сатып алынған мүлікті балансқа қабылдап, оның пайдаланылуын қамтамасыз ету — қажеттісін қалдырыңыз].',
        'Жоба бойынша байланыс тұлғасы: [Т.А.Ә., лауазымы, телефоны, e-mail].',
      ],
      signer: ['[Бірінші басшының лауазымы]', '[Қолы]', '[Т.А.Ә.]'],
    },
    budget: {
      file: '03-smeta.xlsx', sheet: 'Смета', title: 'ЖОБА ШЫҒЫСТАРЫНЫҢ СМЕТАСЫ',
      meta: ['Өтініш беруші', 'Жобаның атауы', 'Қор бағдарламасы', 'Іске асыру мерзімі'],
      head: ['№', 'Шығыс бабы', 'Өлш. бірл.', 'Саны', 'Бірлік бағасы, ₸', 'Сомасы, ₸', 'Қор қаражаты, ₸', 'Қоса қаржыландыру, ₸', 'Негіздеме'],
      cats: ['Жоба қатысушыларының еңбекақысы (салықтар мен міндетті төлемдерді қоса)', 'Жабдықтар, аспаптар, бағдарламалық қамтамасыз ету', 'Материалдар, реактивтер, жинақтауыштар', 'Бөгде ұйымдардың қызметтері (зертханалық, талдамалық, аударма және т.б.)', 'Далалық жұмыстар, экспедициялар, деректер жинау', 'Іссапарлар, тағылымдамалар, іс-шараларға қатысу', 'Жарияланымдар, ашық қолжетімділік, нәтижелерді тарату', 'Нәтижелерді құқықтық қорғау, рұқсаттар, сараптамалар', 'Үстеме шығыстар (негізделген, 10%-дан аспайды)', 'Өзге тікелей шығыстар'],
      ex: ['Мысалы: жоба жетекшісі, 0,5 ставка', 'ай', 12, 450000, 'Ұйым бойынша орташа ставка'],
      sub: 'Бап бойынша жиыны', total: 'ЖОБА БОЙЫНША ЖИЫНЫ', share: 'Қор қаражатының үлесі',
      legend: 'Сары ұяшықтарды толтырыңыз. Сомалар автоматты түрде есептеледі. Мысал жолын өз деректеріңізбен ауыстырыңыз; қажет болса, бап ішіне жол қосыңыз.',
    },
    zip: 'qujat-ulgileri.zip',
  },
  en: {
    fund: 'Science and Education Endowment Fund (corporate endowment fund)',
    site: 'endowment-fund.kz · endowment@alageum.com',
    hint: 'Fill in or delete the fields in square brackets. Grey guidance notes can be deleted once completed.',
    sign: ['Signature', 'Full name', 'Date', 'Stamp (for organisations)'],
    app: {
      file: '01-application.docx', title: 'APPLICATION', sub: 'for charitable assistance (a grant) from the Fund',
      s1: '1. Applicant details',
      f1: ['Organisation name / applicant’s full name', 'BIN / IIN', 'Registered and actual address', 'Head of organisation (name, position)', 'Project lead (name, position)', 'Phone', 'E-mail'],
      s2: '2. Project details',
      progL: 'Fund programme', progs: ['Support for Education', 'Support for Science, Research and Technology', 'Support for Innovation and Technology Commercialisation (incl. AI Sana)'],
      f2: ['Project title', 'Area of support', 'Implementation period (start — end)', 'Amount requested, ₸', 'Co-funding, ₸ (source), if any', 'Total project cost, ₸'],
      s3: '3. Project summary', s3h: 'Up to 500 characters: the problem, the goal, what will be done and what beneficiaries will gain.',
      s4: '4. Expected results', s4h: 'List 3–5 measurable results (details go in the project description).',
      s5: '5. Other funding', s5h: 'State whether the project or any of its costs has received funding from public, private or other sources, or whether you have applied to other funds. If not, write “none”.',
      s6: '6. Attached documents',
      att: ['Project description (up to 10 pages)', 'Budget', 'CVs of the project lead and team', 'Letter of support from your organisation', 'Other documents: [list]'],
      s7: '7. Applicant’s declarations',
      conf: ['The information in this application and its annexes is accurate and complete.', 'There is no conflict of interest with the Fund’s staff or governing bodies (or it is disclosed in an annex).', 'The same costs are not funded from other sources (no double funding).', 'The applicant agrees to monitoring, reporting and audits of the use of funds.', 'The applicant consents to the collection and processing of personal data as needed to review the application.'],
    },
    desc: {
      file: '02-project-description.docx', title: 'PROJECT DESCRIPTION', sub: 'Maximum 10 pages (12 pt font, 1.15 line spacing)',
      meta: ['Project title', 'Applicant', 'Fund programme'],
      secs: [
        ['1. Rationale and problem statement', 'What problem the project addresses, why it matters for Kazakhstan and who benefits. Include data and sources.'],
        ['2. Goal and objectives', 'One goal and 3–5 specific objectives.'],
        ['3. Novelty and significance', 'For research projects: scientific novelty and hypothesis; for education projects: how it improves on existing solutions; for innovation projects: technology readiness level (TRL) and market.'],
        ['4. Methodology and approach', 'How the objectives will be achieved: methods, stages, data and infrastructure used.'],
        ['5. Work plan', null, 'plan'],
        ['6. Project team', 'Project lead and key members: role, qualifications and time commitment. CVs are attached separately.'],
        ['7. Infrastructure and resources', 'Equipment, labs, data and partners already available, and what needs to be acquired.'],
        ['8. Expected results and indicators', null, 'kpi'],
        ['9. Risks and mitigation', 'Scientific, technical, financial, legal and other risks.'],
        ['10. Ethics, data and intellectual property', 'Whether ethical approvals and permits are needed; how data will be stored; who will own the results.'],
        ['11. Dissemination and sustainability', 'Publications, adoption, and how results will be used after funding ends.'],
      ],
      plan: ['No.', 'Stage and activities', 'Timing', 'Stage output'],
      kpi: ['Indicator', 'Unit', 'Target', 'Means of verification'],
      kpiEx: ['Example: teachers trained', 'people', '120', 'List, certificates'],
    },
    cv: {
      file: '04-cv.docx', title: 'PROJECT TEAM MEMBER CV', sub: 'Complete one for the project lead and each key team member',
      f: ['Full name', 'Role in the project', 'Employer and position', 'Academic degree / title (if any)', 'E-mail, phone', 'ORCID / Scopus ID / h-index (research projects)'],
      edu: 'Education', eduH: ['Years', 'Institution', 'Field, degree'],
      job: 'Work experience (last 10 years)', jobH: ['Years', 'Organisation', 'Position, key responsibilities'],
      pub: 'Key publications, projects, grants (up to 5)', pubH: 'For each: title, year, your role, funder / journal.',
      lang: 'Languages', other: 'Additional information',
    },
    letter: {
      file: '05-letter-of-support.docx', blank: '[ORGANISATION LETTERHEAD]', out: 'Ref. No. [___] dated [__ ________ 20__]',
      to: ['To the Director', 'Science and Education Endowment Fund', '(corporate endowment fund)'],
      title: 'LETTER OF SUPPORT',
      body: [
        '[Organisation name] supports the application by [project lead’s name / applicant] to the Fund’s charitable programme “[programme name]” with the project “[project title]”.',
        'The project is aligned with the priorities of [the organisation] and aims to [briefly — expected impact for the organisation and beneficiaries].',
        'If the project is supported, [the organisation] undertakes to: [provide access to infrastructure / labs / data; ensure staff participation; provide co-funding of ___ ₸; take acquired equipment on its balance sheet and maintain it — keep what applies].',
        'Project contact: [name, position, phone, e-mail].',
      ],
      signer: ['[Position of the head of organisation]', '[Signature]', '[Full name]'],
    },
    budget: {
      file: '03-budget.xlsx', sheet: 'Budget', title: 'PROJECT BUDGET',
      meta: ['Applicant', 'Project title', 'Fund programme', 'Implementation period'],
      head: ['No.', 'Cost item', 'Unit', 'Qty', 'Unit price, ₸', 'Amount, ₸', 'Fund share, ₸', 'Co-funding, ₸', 'Justification'],
      cats: ['Staff costs of project members (incl. taxes and mandatory contributions)', 'Equipment, instruments, software', 'Materials, reagents, components', 'Third-party services (lab, analytical, translation, etc.)', 'Fieldwork, expeditions, data collection', 'Travel, internships, event participation', 'Publications, open access, dissemination', 'IP protection, permits, reviews', 'Overheads (justified, max. 10%)', 'Other direct costs'],
      ex: ['Example: project lead, 0.5 FTE', 'month', 12, 450000, 'Average rate at the organisation'],
      sub: 'Subtotal', total: 'PROJECT TOTAL', share: 'Fund share',
      legend: 'Fill in the yellow cells. Totals are calculated automatically. Replace the example row with your data; add rows within an item if needed.',
    },
    zip: 'document-templates.zip',
  },
};
